In [1]:
from sklearn.datasets import make_classification
import numpy as np
import pandas as pd

In [15]:
X, y = make_classification(n_samples=100, n_features=2, n_informative=1,n_redundant=0,
                           n_classes=2, n_clusters_per_class=1, random_state=41,hypercube=False,class_sep=10)

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
X

array([[ 0.19924745, -0.11697552],
       [-0.24882029, -0.73115232],
       [-0.3544904 , -0.7081059 ],
       [-1.59086506, -2.01199214],
       [-0.20083951,  1.63493163],
       [-0.83241122,  0.15599044],
       [-1.79207014,  1.07782053],
       [ 0.0856607 ,  0.80626713],
       [-0.55865299,  0.74859527],
       [-1.95974262,  0.75152794],
       [-1.77828947, -0.90114581],
       [-1.77985853, -0.1815243 ],
       [-0.02194151, -2.98092432],
       [ 0.80563431,  1.20500136],
       [-1.82701214,  0.78302407],
       [ 0.38730728,  0.42968688],
       [-0.14108668, -0.73229726],
       [-1.87955941, -0.83930476],
       [-0.18232911,  0.83727062],
       [-1.77059533, -0.10255323],
       [-2.27658028,  0.65867001],
       [-2.06519502,  0.92649819],
       [-1.31690551,  0.10216193],
       [ 1.61043259,  0.46886454],
       [-1.21650394,  0.45432938],
       [ 0.6139723 ,  1.8613386 ],
       [-1.78760957, -0.79255991],
       [-1.04149161, -1.0004391 ],
       [-2.40067584,

In [10]:
sns.scatterplot(x= X[:,0],y = X[:,1],hue = y)

<Axes: >

In [28]:
def step(x):
    if x >=0:
        return 1
    else:
        return 0

In [38]:
def perceptron(X,y,epochs = 1000):
    weights = np.ones(X.shape[1]+1)
    lr = 0.1
    
    for _ in range(epochs):
        j = np.random.randint(0,X.shape[0])
        x = np.insert(X[j],0,1)
        y_hat = step(np.dot(x,weights))
        weights = weights + lr * (y[j] - y_hat)*x
    
    return weights

In [36]:
weights = np.ones(X.shape[1])
weights

array([1., 1.])

In [39]:
j = np.random.randint(0,X.shape[0])
np.insert(X[j],0,1)

array([ 1.        , -1.04149161, -1.0004391 ])

In [43]:
perceptron(X,y)
intercept_ = perceptron(X,y)[0]
coef_ = perceptron(X,y)[[1,2]]
print(f"coef_ = {coef_}\nintercept = {intercept_}")

coef_ = [1.43997014 0.13629215]
intercept = 1.0


In [55]:
m = -(coef_[0]/coef_[1])
b = -(intercept_/coef_[1])

In [56]:
x_input = np.linspace(-3,3,100)
y_input = m*x_input + b

In [74]:
plt.figure(figsize=(10,6))
plt.plot(x_input,y_input,color = 'red')
plt.scatter(X[:,0],X[:,1],c = y)
plt.ylim(-4,2.5)

(-4.0, 2.5)